### ISSUE TITLE
Restart after errors

### ISSUE THREAD

**Issue by lorensr** [jkrup/meteor-now#103]
Does meteor-now restart after errors? 

From now docs:
> When an instance restarts for any reason (or exit code), we automatically restart the instance, so supervisor-like wrappers are not necessary. For example forever, nodemon or pm are not necessary for an application to always stay running.

My server does not successfully restart after errors. The last lines in the logs are:

```
npm install
File does not exist “/home/nowuser/src/package.json”
```

After which I get a 502 error when trying to reach the site. 

Full log:

```
03/30 09:56 AM (32m)
Failed on error code 504
Retried 1 time
03/30 09:56 AM (32m)
Failed on error code 504
Retried 2 time
Failed on error code 504
03/30 09:56 AM (32m)
Retried 3 time
03/30 09:56 AM (32m)
Failed on error code 504
Retried 4 time
03/30 09:56 AM (32m)
Failed on error code 504
Retried 5 time
03/30 09:56 AM (32m)
Error Code- 504 “Gateway Time-out”
03/30 09:56 AM (32m)
/usr/src/app/bundle/programs/server/npm/node_modules/winston/node_modules/async/lib/async.js:38
           if (called) throw new Error(“Callback was already called.“);
                       ^

Error: Callback was already called.
   at /usr/src/app/bundle/programs/server/npm/node_modules/winston/node_modules/async/lib/async.js:38:31
   at /usr/src/app/bundle/programs/server/npm/node_modules/winston/lib/winston/logger.js:238:16
   at logged (/usr/src/app/bundle/programs/server/npm/node_modules/winston-loggly-bulk/lib/winston-loggly.js:129:5)
   at /usr/src/app/bundle/programs/server/npm/node_modules/node-loggly-bulk/lib/loggly/client.js:199:9
   at Request._callback (/usr/src/app/bundle/programs/server/npm/node_modules/node-loggly-bulk/lib/loggly/common.js:189:9)
   at Request.self.callback (/usr/src/app/bundle/programs/server/npm/node_modules/request/request.js:188:22)
   at emitTwo (events.js:126:13)
   at Request.emit (events.js:214:7)
   at Request.<anonymous> (/usr/src/app/bundle/programs/server/npm/node_modules/request/request.js:1171:10)
   at emitOne (events.js:116:13)
03/30 09:56 AM (31m)
npm install
03/30 09:56 AM (31m)
File does not exist “/home/nowuser/src/package.json”
```

**Comment by timneutkens** [comment]
Could be related to https://github.com/jkrup/meteor-now/pull/101

**Comment by jkrup** [comment]
This was related to an issue with now, which has been resolved as per support.
