### ISSUE TITLE
Meteor 1.7 mongo error

### ISSUE THREAD

**Issue by trinicoder** [jkrup/meteor-now#114]
**Describe the bug**
meteor-now --public  does not deploy app

**To Reproduce**
-`meteor-now --public`
-See error
```
> [0] 2018-07-02 21:12:55,165 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 140052410180240 for <Subprocess at 140052410093440 with name node in state RUNNING> (stdout)>
> [0] 2018-07-02 21:12:55,165 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140052409683048 for <Subprocess at 140052410093440 with name node in state RUNNING> (stderr)>
> [0] 2018-07-02 21:12:55,165 INFO exited: node (exit status 1; not expected)
> [0] 2018-07-02 21:12:55,165 DEBG received SIGCLD indicating a child quit
> [0] 2018-07-02 21:12:57,168 INFO success: node entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> [0] 2018-07-02 21:12:57,189 DEBG 'node' stderr output:
> [0] Note: you are using a pure-JavaScript implementation of bcrypt.
> [0] While this implementation will work correctly, it is known to be
> [0] approximately three times slower than the native implementation.
> [0] In order to use the native implementation instead, run
> [0]
> [0]   meteor npm install --save bcrypt
> [0]
> [0] in the root directory of your application.
> [0]
> [0] 2018-07-02 21:12:57,217 DEBG 'mongo' stdout output:
> [0] Mon Jul  2 21:12:57.216 [initandlisten] connection accepted from 127.0.0.1:35408 #28 (1 connection now open)
> [0]
> [0] 2018-07-02 21:12:57,229 DEBG 'mongo' stdout output:
> [0] Mon Jul  2 21:12:57.229 [conn28] end connection 127.0.0.1:35408 (0 connections now open)
> [0]
> [0] 2018-07-02 21:12:57,232 DEBG 'node' stderr output:
> [0]
> [0] /usr/src/app/bundle/programs/server/node_modules/fibers/future.js:313
> [0]                                           throw(ex);
> [0]                                           ^
> [0] MongoError: Server at 127.0.0.1:27017 reports wire version 0, but this version of Node.js Driver requires at least 2 (MongoDB2.6).
> [0]     at /usr/src/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:379:39
> [0]     at /usr/src/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:544:18
> [0]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
> [0]     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
> [0]
> [0] 2018-07-02 21:12:57,238 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 140052410180240 for <Subprocess at 140052410093440 with name node in state RUNNING> (stdout)>
> [0] 2018-07-02 21:12:57,238 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140052409682976 for <Subprocess at 140052410093440 with name node in state RUNNING> (stderr)>
> [0] 2018-07-02 21:12:57,238 INFO exited: node (exit status 1; not expected)
> [0] 2018-07-02 21:12:57,238 DEBG received SIGCLD indicating a child quit
> [0] 2018-07-02 21:12:58,239 INFO spawned: 'node' with pid 356
> [0] In order to use the native implementation instead, run
> [0]
> [0]   meteor npm install --save bcrypt
> [0]
> [0] in the root directory of your application.
> [0]
> [0] 2018-07-02 21:12:59,180 DEBG 'mongo' stdout output:
> [0] Mon Jul  2 21:12:59.180 [initandlisten] connection accepted from 127.0.0.1:35550 #29 (1 connection now open)
> [0]
> Error! Instance verification timed out (3m)
> Read more: https://err.sh/now-cli/verification-timeout
```

**Expected behavior**
App deployed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser NA
+ meteor-now@0.6.1
+ now@11.2.5

**Comment by trinicoder** [comment]
Now I am getting this after reinstall of meteor-now...
This is the final part of the output.
```
> ▲ Storing image
> Build completed
> Verifying instantiation in sfo1
> Error! Instance verification timed out (3m)
> Read more: https://err.sh/now-cli/verification-timeout
```

**Comment by jkrup** [comment]
Hi @trinicoder  could you try `npm install -g meteor-now@beta` and see if that works for you?

**Comment by trinicoder** [comment]
It seems the deploy my app successful as indicated by the command line output.But  it did not work initial on the web but I check it a day later (now) and now it works..

**Comment by trinicoder** [comment]
So everything is working well again. No issues! Thanks for making this tool available.
