### ISSUE TITLE
Unknown error: TypeError: stdin.setRawMode is not a function

### ISSUE THREAD

**Issue by yoitsro** [jkrup/meteor-now#46]
When there should be a prompt displayed, meteor-now receives an error here:

```
TypeError: stdin.setRawMode is not a function
    at Promise (/Users/ro/.nvm/versions/node/v6.10.2/lib/node_modules/now/build/lib/utils/input/prompt-bool.js:24:11)
    at module.exports (/Users/ro/.nvm/versions/node/v6.10.2/lib/node_modules/now/build/lib/utils/input/prompt-bool.js:18:10)
    at /Users/ro/.nvm/versions/node/v6.10.2/lib/node_modules/now/build/bin/now-deploy.js:617:23
    at next (native)
    at c (/Users/ro/.nvm/versions/node/v6.10.2/lib/node_modules/now/build/bin/now-deploy.js:736:99)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Is there a particular version of Node I should be running to avoid this issue?

**Comment by UShan89** [comment]
@yoitsro I tried this `node -p -e "Boolean(process.stdin.setRawMode)"` and got `true` back. 

`node -p -e "process.stdin.setRawMode"` returned `[Function]` 

I am on node v6.10.2. I do not see this problem. Maybe the has something to do with now-cli?

**Comment by purplecones** [comment]
The stacktrace seems to point to now in the node_module folder so I also think it might be related to now-cli. What version are you running? Try just running `npm install -g now meteor-now` to get the latest and try again. Otherwise if it still happens, head over to the now repo and check if anyone else encountered the problem.
