### ISSUE TITLE
After first install, I get: SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by tomyo** [jkrup/meteor-now#56]
After installing, on first command (now --login), I get this:

```
const { resolve } = require('path')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
```

Using ubuntu 17.04, nodejs version v4.7.2.

This is the installing log
```
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated isarray@2.0.1: Just use Array.isArray directly
/usr/local/bin/meteor-now -> /usr/local/lib/node_modules/meteor-now/index.js
/usr/local/bin/now -> /usr/local/lib/node_modules/now/build/bin/now.js
/usr/local/lib
├─┬ meteor-now@0.2.2 
│ ├─┬ babel-polyfill@6.23.0 
│ │ ├── babel-runtime@6.23.0 
│ │ ├── core-js@2.4.1 
│ │ └── regenerator-runtime@0.10.5 
│ ├── cli-spinners@1.0.0 
│ ├── colors@1.1.2 
│ ├─┬ delete@0.3.2 
│ │ ├── async@1.5.2 
│ │ ├── bluebird@3.5.0 
│ │ ├─┬ extend-shallow@2.0.1 
│ │ │ └── is-extendable@0.1.1 
│ │ ├── lazy-cache@1.0.4 
│ │ ├─┬ matched@0.4.4 
│ │ │ ├── arr-union@3.1.0 
│ │ │ ├── async-array-reduce@0.2.1 
│ │ │ ├── fs-exists-sync@0.1.0 
│ │ │ ├─┬ glob@7.1.2 
│ │ │ │ ├── fs.realpath@1.0.0 
│ │ │ │ ├─┬ inflight@1.0.6 
│ │ │ │ │ └── wrappy@1.0.2 
│ │ │ │ ├── inherits@2.0.3 
│ │ │ │ ├─┬ minimatch@3.0.4 
│ │ │ │ │ └─┬ brace-expansion@1.1.7 
│ │ │ │ │   ├── balanced-match@0.4.2 
│ │ │ │ │   └── concat-map@0.0.1 
│ │ │ │ ├── once@1.4.0 
│ │ │ │ └── path-is-absolute@1.0.1 
│ │ │ ├─┬ has-glob@0.1.1 
│ │ │ │ └─┬ is-glob@2.0.1 
│ │ │ │   └── is-extglob@1.0.0 
│ │ │ ├── is-valid-glob@0.3.0 
│ │ │ ├─┬ lazy-cache@2.0.2 
│ │ │ │ └─┬ set-getter@0.1.0 
│ │ │ │   └─┬ to-object-path@0.3.0 
│ │ │ │     └─┬ kind-of@3.2.2 
│ │ │ │       └── is-buffer@1.1.5 
│ │ │ └─┬ resolve-dir@0.1.1 
│ │ │   ├─┬ expand-tilde@1.2.2 
│ │ │   │ └── os-homedir@1.0.2 
│ │ │   └─┬ global-modules@0.2.3 
│ │ │     ├─┬ global-prefix@0.1.5 
│ │ │     │ ├─┬ homedir-polyfill@1.0.1 
│ │ │     │ │ └── parse-passwd@1.0.0 
│ │ │     │ ├── ini@1.3.4 
│ │ │     │ └─┬ which@1.2.14 
│ │ │     │   └── isexe@2.0.0 
│ │ │     └── is-windows@0.2.0 
│ │ └── rimraf@2.6.1 
│ ├── lodash@4.17.4 
│ ├── minimist@1.2.0 
│ ├─┬ now-client@0.7.0 
│ │ ├─┬ request@2.81.0 
│ │ │ ├── aws-sign2@0.6.0 
│ │ │ ├── aws4@1.6.0 
│ │ │ ├── caseless@0.12.0 
│ │ │ ├─┬ combined-stream@1.0.5 
│ │ │ │ └── delayed-stream@1.0.0 
│ │ │ ├── extend@3.0.1 
│ │ │ ├── forever-agent@0.6.1 
│ │ │ ├─┬ form-data@2.1.4 
│ │ │ │ └── asynckit@0.4.0 
│ │ │ ├─┬ har-validator@4.2.1 
│ │ │ │ ├─┬ ajv@4.11.8 
│ │ │ │ │ ├── co@4.6.0 
│ │ │ │ │ └─┬ json-stable-stringify@1.0.1 
│ │ │ │ │   └── jsonify@0.0.0 
│ │ │ │ └── har-schema@1.0.5 
│ │ │ ├─┬ hawk@3.1.3 
│ │ │ │ ├── boom@2.10.1 
│ │ │ │ ├── cryptiles@2.0.5 
│ │ │ │ ├── hoek@2.16.3 
│ │ │ │ └── sntp@1.0.9 
│ │ │ ├─┬ http-signature@1.1.1 
│ │ │ │ ├── assert-plus@0.2.0 
│ │ │ │ ├─┬ jsprim@1.4.0 
│ │ │ │ │ ├── assert-plus@1.0.0 
│ │ │ │ │ ├── extsprintf@1.0.2 
│ │ │ │ │ ├── json-schema@0.2.3 
│ │ │ │ │ └── verror@1.3.6 
│ │ │ │ └─┬ sshpk@1.13.0 
│ │ │ │   ├── asn1@0.2.3 
│ │ │ │   ├── assert-plus@1.0.0 
│ │ │ │   ├── bcrypt-pbkdf@1.0.1 
│ │ │ │   ├─┬ dashdash@1.14.1 
│ │ │ │   │ └── assert-plus@1.0.0 
│ │ │ │   ├── ecc-jsbn@0.1.1 
│ │ │ │   ├─┬ getpass@0.1.7 
│ │ │ │   │ └── assert-plus@1.0.0 
│ │ │ │   ├── jodid25519@1.0.2 
│ │ │ │   ├── jsbn@0.1.1 
│ │ │ │   └── tweetnacl@0.14.5 
│ │ │ ├── is-typedarray@1.0.0 
│ │ │ ├── isstream@0.1.2 
│ │ │ ├── json-stringify-safe@5.0.1 
│ │ │ ├─┬ mime-types@2.1.15 
│ │ │ │ └── mime-db@1.27.0 
│ │ │ ├── oauth-sign@0.8.2 
│ │ │ ├── performance-now@0.2.0 
│ │ │ ├── qs@6.4.0 
│ │ │ ├── safe-buffer@5.0.1 
│ │ │ ├── stringstream@0.0.5 
│ │ │ ├─┬ tough-cookie@2.3.2 
│ │ │ │ └── punycode@1.4.1 
│ │ │ ├── tunnel-agent@0.6.0 
│ │ │ └── uuid@3.0.1 
│ │ └─┬ request-promise-native@1.0.4 
│ │   ├── request-promise-core@1.1.1 
│ │   └── stealthy-require@1.1.1 
│ ├─┬ ora@1.2.0 
│ │ ├─┬ chalk@1.1.3 
│ │ │ ├── ansi-styles@2.2.1 
│ │ │ ├── escape-string-regexp@1.0.5 
│ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ └── ansi-regex@2.1.1 
│ │ │ ├── strip-ansi@3.0.1 
│ │ │ └── supports-color@2.0.0 
│ │ ├─┬ cli-cursor@2.1.0 
│ │ │ └─┬ restore-cursor@2.0.0 
│ │ │   ├─┬ onetime@2.0.1 
│ │ │   │ └── mimic-fn@1.1.0 
│ │ │   └── signal-exit@3.0.2 
│ │ └── log-symbols@1.0.2 
│ ├─┬ promise-spawner@1.1.3 
│ │ ├── bluebird@1.2.4 
│ │ └─┬ through2@0.4.2 
│ │   ├─┬ readable-stream@1.0.34 
│ │   │ ├── core-util-is@1.0.2 
│ │   │ ├── isarray@0.0.1 
│ │   │ └── string_decoder@0.10.31 
│ │   └─┬ xtend@2.1.2 
│ │     └── object-keys@0.4.0 
│ └─┬ split-file@2.0.0-alpha.1 
│   └── async@2.4.0 
└─┬ now@5.3.1 
  ├── @google/maps@0.3.1 
  ├── ansi-escapes@2.0.0 
  ├── ansi-regex@2.1.1 
  ├── arr-flatten@1.0.3 
  ├── array-unique@0.3.2 
  ├─┬ async-retry@0.3.0 
  │ └── retry@0.10.1 
  ├─┬ async-to-gen@1.3.3 
  │ ├── babylon@6.17.1 
  │ └─┬ magic-string@0.19.1 
  │   └── vlq@0.2.2 
  ├── bytes@2.5.0 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├── has-ansi@2.0.0 
  │ └── supports-color@2.0.0 
  ├─┬ clipboardy@1.1.2 
  │ └─┬ execa@0.6.3 
  │   ├─┬ npm-run-path@2.0.2 
  │   │ └── path-key@2.0.1 
  │   ├── p-finally@1.0.0 
  │   ├── signal-exit@3.0.2 
  │   └── strip-eof@1.0.0 
  ├─┬ credit-card@3.0.1 
  │ ├── lodash.merge@4.6.0 
  │ └── reach@1.0.0 
  ├─┬ cross-spawn@5.1.0 
  │ ├─┬ lru-cache@4.0.2 
  │ │ ├── pseudomap@1.0.2 
  │ │ └── yallist@2.1.2 
  │ ├─┬ shebang-command@1.2.0 
  │ │ └── shebang-regex@1.0.0 
  │ └─┬ which@1.2.14 
  │   └── isexe@2.0.0 
  ├── dateformat@2.0.0 
  ├── docker-file-parser@1.0.2 
  ├── dotenv@4.0.0 
  ├─┬ download@6.1.0 
  │ ├─┬ caw@2.0.0 
  │ │ ├─┬ get-proxy@1.1.0 
  │ │ │ └─┬ rc@1.2.1 
  │ │ │   ├── deep-extend@0.4.2 
  │ │ │   └── strip-json-comments@2.0.1 
  │ │ └── tunnel-agent@0.4.3 
  │ ├── content-disposition@0.5.2 
  │ ├─┬ decompress@4.2.0 
  │ │ ├─┬ decompress-tar@4.1.0 
  │ │ │ ├── file-type@3.9.0 
  │ │ │ └─┬ tar-stream@1.5.4 
  │ │ │   ├── bl@1.2.1 
  │ │ │   ├── end-of-stream@1.4.0 
  │ │ │   ├─┬ readable-stream@2.2.9 
  │ │ │   │ ├── buffer-shims@1.0.0 
  │ │ │   │ ├── core-util-is@1.0.2 
  │ │ │   │ ├── isarray@1.0.0 
  │ │ │   │ ├── process-nextick-args@1.0.7 
  │ │ │   │ ├── string_decoder@1.0.1 
  │ │ │   │ └── util-deprecate@1.0.2 
  │ │ │   └── xtend@4.0.1 
  │ │ ├─┬ decompress-tarbz2@4.1.0 
  │ │ │ ├─┬ seek-bzip@1.0.5 
  │ │ │ │ └─┬ commander@2.8.1 
  │ │ │ │   └── graceful-readlink@1.0.1 
  │ │ │ └─┬ unbzip2-stream@1.0.11 
  │ │ │   └─┬ buffer@3.6.0 
  │ │ │     ├── base64-js@0.0.8 
  │ │ │     └── ieee754@1.1.8 
  │ │ ├── decompress-targz@4.0.0 
  │ │ ├─┬ decompress-unzip@4.0.1 
  │ │ │ ├─┬ get-stream@2.3.1 
  │ │ │ │ └─┬ pinkie-promise@2.0.1 
  │ │ │ │   └── pinkie@2.0.4 
  │ │ │ └─┬ yauzl@2.8.0 
  │ │ │   ├── buffer-crc32@0.2.13 
  │ │ │   └─┬ fd-slicer@1.0.1 
  │ │ │     └── pend@1.2.0 
  │ │ ├── graceful-fs@4.1.11 
  │ │ └─┬ strip-dirs@2.0.0 
  │ │   └── is-natural-number@4.0.1 
  │ ├─┬ filenamify@2.0.0 
  │ │ ├── filename-reserved-regex@2.0.0 
  │ │ ├── strip-outer@1.0.0 
  │ │ └── trim-repeated@1.0.0 
  │ ├── get-stream@3.0.0 
  │ ├─┬ got@6.7.1 
  │ │ ├─┬ create-error-class@3.0.2 
  │ │ │ └── capture-stack-trace@1.0.0 
  │ │ ├── duplexer3@0.1.4 
  │ │ ├── is-redirect@1.0.0 
  │ │ ├── is-retry-allowed@1.1.0 
  │ │ ├── lowercase-keys@1.0.0 
  │ │ ├── safe-buffer@5.0.1 
  │ │ ├── timed-out@4.0.1 
  │ │ ├── unzip-response@2.0.1 
  │ │ └─┬ url-parse-lax@1.0.0 
  │ │   └── prepend-http@1.0.4 
  │ ├── make-dir@1.0.0 
  │ ├─┬ p-event@1.2.0 
  │ │ └── p-timeout@1.1.1 
  │ └── pify@2.3.0 
  ├── email-prompt@0.3.0 
  ├── email-validator@1.0.7 
  ├── epipebomb@1.0.0 
  ├─┬ fs-promise@2.0.3 
  │ ├── any-promise@1.3.0 
  │ ├─┬ fs-extra@2.1.2 
  │ │ └── jsonfile@2.4.0 
  │ ├── mz@2.6.0 
  │ └─┬ thenify-all@1.6.0 
  │   └── thenify@3.3.0 
  ├─┬ glob@7.1.1 
  │ ├── fs.realpath@1.0.0 
  │ ├─┬ inflight@1.0.6 
  │ │ └── wrappy@1.0.2 
  │ ├── inherits@2.0.3 
  │ ├─┬ minimatch@3.0.4 
  │ │ └─┬ brace-expansion@1.1.7 
  │ │   ├── balanced-match@0.4.2 
  │ │   └── concat-map@0.0.1 
  │ ├── once@1.4.0 
  │ └── path-is-absolute@1.0.1 
  ├── ignore@3.3.0 
  ├── ini@1.3.4 
  ├─┬ inquirer@3.0.6 
  │ ├── ansi-escapes@1.4.0 
  │ ├─┬ cli-cursor@2.1.0 
  │ │ └─┬ restore-cursor@2.0.0 
  │ │   └─┬ onetime@2.0.1 
  │ │     └── mimic-fn@1.1.0 
  │ ├── cli-width@2.1.0 
  │ ├── external-editor@2.0.1 
  │ ├── figures@2.0.0 
  │ ├── lodash@4.17.4 
  │ ├── mute-stream@0.0.7 
  │ ├─┬ run-async@2.3.0 
  │ │ └── is-promise@2.1.0 
  │ ├── rx@4.1.0 
  │ ├─┬ string-width@2.0.0 
  │ │ └── is-fullwidth-code-point@2.0.0 
  │ └── through@2.3.8 
  ├── is-url@1.2.2 
  ├── lodash.range@3.2.0 
  ├── minimist@1.2.0 
  ├── ms@2.0.0 
  ├─┬ node-fetch@1.6.3 
  │ ├─┬ encoding@0.1.12 
  │ │ └── iconv-lite@0.4.17 
  │ └── is-stream@1.1.0 
  ├─┬ opn@5.0.0 
  │ └── is-wsl@1.1.0 
  ├─┬ ora@1.2.0 
  │ ├── cli-spinners@1.0.0 
  │ └── log-symbols@1.0.2 
  ├── printf@0.2.5 
  ├── progress@2.0.0 
  ├── psl@1.1.18 
  ├── resumer@0.0.0 
  ├─┬ single-line-log@1.1.2 
  │ └─┬ string-width@1.0.2 
  │   ├── code-point-at@1.1.0 
  │   └─┬ is-fullwidth-code-point@1.0.0 
  │     └── number-is-nan@1.0.1 
  ├─┬ socket.io-client@2.0.1 
  │ ├── backo2@1.0.2 
  │ ├── base64-arraybuffer@0.1.5 
  │ ├── component-bind@1.0.0 
  │ ├── component-emitter@1.2.1 
  │ ├─┬ debug@2.6.4 
  │ │ └── ms@0.7.3 
  │ ├─┬ engine.io-client@3.1.1 
  │ │ ├── component-inherit@0.0.3 
  │ │ ├─┬ engine.io-parser@2.1.1 
  │ │ │ ├── after@0.8.2 
  │ │ │ ├── arraybuffer.slice@0.0.6 
  │ │ │ └── blob@0.0.4 
  │ │ ├── parsejson@0.0.3 
  │ │ ├── parseqs@0.0.5 
  │ │ ├─┬ ws@2.3.1 
  │ │ │ └── ultron@1.1.0 
  │ │ ├── xmlhttprequest-ssl@1.5.3 
  │ │ └── yeast@0.1.2 
  │ ├── has-cors@1.1.0 
  │ ├── indexof@0.0.1 
  │ ├── object-component@0.0.3 
  │ ├─┬ parseuri@0.0.5 
  │ │ └─┬ better-assert@1.0.2 
  │ │   └── callsite@1.0.0 
  │ ├─┬ socket.io-parser@3.1.2 
  │ │ ├─┬ has-binary2@1.0.2 
  │ │ │ └── isarray@2.0.1 
  │ │ └── isarray@2.0.1 
  │ └── to-array@0.1.4 
  ├── split-array@1.0.1 
  ├── strip-ansi@3.0.1 
  ├─┬ stripe@4.19.0 
  │ ├── bluebird@2.11.0 
  │ ├── lodash.isplainobject@4.0.6 
  │ ├── object-assign@4.1.1 
  │ └── qs@6.0.4 

  │ └── has-flag@1.0.0 
  ├── text-table@0.2.0 
  ├─┬ tmp-promise@1.0.3 
  │ ├── bluebird@3.5.0 
  │ └─┬ tmp@0.0.31 
  │   └── os-tmpdir@1.0.2 
  └─┬ update-notifier@2.1.0 
    ├─┬ boxen@1.1.0 
    │ ├── ansi-align@2.0.0 
    │ ├── camelcase@4.1.0 
    │ ├── cli-boxes@1.0.0 
    │ ├─┬ term-size@0.1.1 
    │ │ └─┬ execa@0.4.0 
    │ │   ├── cross-spawn-async@2.2.5 
    │ │   ├── npm-run-path@1.0.0 
    │ │   └── path-key@1.0.0 
    │ └─┬ widest-line@1.0.0 
    │   └─┬ string-width@1.0.2 
    │     └── is-fullwidth-code-point@1.0.0 
    ├─┬ configstore@3.1.0 
    │ ├─┬ dot-prop@4.1.1 
    │ │ └── is-obj@1.0.1 
    │ ├─┬ unique-string@1.0.0 
    │ │ └── crypto-random-string@1.0.0 
    │ └─┬ write-file-atomic@2.1.0 
    │   ├── imurmurhash@0.1.4 
    │   └── slide@1.1.6 
    ├── is-npm@1.0.0 
    ├─┬ latest-version@3.1.0 
    │ └─┬ package-json@4.0.1 
    │   ├── registry-auth-token@3.3.1 
    │   └── registry-url@3.1.0 
    ├── lazy-req@2.0.0 
    ├─┬ semver-diff@2.1.0 
    │ └── semver@5.3.0 
    └── xdg-basedir@3.0.0 
```

**Comment by tomyo** [comment]
Issue was in old node version.., updated using this thread: https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version
