### ISSUE TITLE
unhandled Error: 1

### ISSUE THREAD

**Issue by boustanihani** [jkrup/meteor-now#57]
I am getting a weird unhandled error while trying to deploy a fresh app, the deploy process never ends, I waited half an hour :)

```
meteor-now -e MONGO_URL=mongodb://user:pass@host:port/db
✔ [METEOR-NOW] - building meteor app
✔ [METEOR-NOW] - preparing build
⠄⡙ [METEOR-NOW] - deploying build (this can take several minutes)Possibly unhandled Error: 1
    at Promise$_rejecter (/home/ubuntu/workspace/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:590:44)
    at /home/ubuntu/workspace/node_modules/promise-spawner/index.js:85:13
    at tryCatch1 (/home/ubuntu/workspace/node_modules/promise-spawner/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/home/ubuntu/workspace/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/ubuntu/workspace/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/home/ubuntu/workspace/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/home/ubuntu/workspace/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:1006:14)
    at Promise$_rejectPromises [as _rejectPromises] (/home/ubuntu/workspace/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:999:10)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/ubuntu/workspace/node_modules/promise-spawner/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/home/ubuntu/workspace/node_modules/promise-spawner/node_modules/bluebird/js/main/async.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
⡋⠀ [METEOR-NOW] - deploying build (this can take several minutes)^C

```

**Comment by purplecones** [comment]
Try redeploying with the `-d` flag to see detailed log of when it fails.

**Comment by boustanihani** [comment]
with the -d flag it magically works :)

**Comment by purplecones** [comment]
Ok glad it works now. It was probably an issue with `now` during upload.

**Comment by snajjar** [comment]
Same problem for me, with -d it works, but without it doesn't...

**Comment by arrygoo** [comment]
Same! only works with `-d`.
