### ISSUE TITLE
Possibly unhandled Error: 1

### ISSUE THREAD

**Issue by hakimelek** [jkrup/meteor-now#62]
During step [METEOR-NOW] - deploying build

I am getting this error. Any help? :)

> Possibly unhandled Error: 1
    at Promise$_rejecter (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:590:44)
    at /usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/index.js:85:13
    at tryCatch1 (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:1006:14)
    at Promise$_rejectPromises [as _rejectPromises] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:999:10)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/async.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by jkrup** [comment]
What version of meteor are you using?

**Comment by hakimelek** [comment]
I was trying to deploy a [VulcanJS](http://vulcanjs.org/) app, which worked! I just cleaned my npm cache!

**Comment by hakimelek** [comment]
duplicate of #57
