### ISSUE TITLE
Possibly unhandled Error: 1; Deploy build without mongo url

### ISSUE THREAD

**Issue by janat08** [jkrup/meteor-now#66]
Using meteor-now gets stuck on deploy build step after logging this.
```[METEOR-NOW] - deploying build (this can take several minutes)Possibly unhan
dled Error: 1
    at Promise$_rejecter (C:\Users\ALERATOR\AppData\Roaming\npm\node_modules\me
teor-now\node_modules\promise-spawner\node_modules\bluebird\js\main\promise.js:
590:44)
    at C:\Users\ALERATOR\AppData\Roaming\npm\node_modules\meteor-now\node_modul
es\promise-spawner\index.js:85:13
    at tryCatch1 (C:\Users\ALERATOR\AppData\Roaming\npm\node_modules\meteor-now
\node_modules\promise-spawner\node_modules\bluebird\js\main\util.js:63:19)
    at Promise$_callHandler [as _callHandler] (C:\Users\ALERATOR\AppData\Roamin
g\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules\bluebir
d\js\main\promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (C:\Use
rs\ALERATOR\AppData\Roaming\npm\node_modules\meteor-now\node_modules\promise-sp
awner\node_modules\bluebird\js\main\promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (C:\Users\ALERATOR\AppDat
a\Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules
\bluebird\js\main\promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (C:\Users\ALERATOR\AppData\
Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules\b
luebird\js\main\promise.js:1006:14)
    at Promise$_rejectPromises [as _rejectPromises] (C:\Users\ALERATOR\AppData\
Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\node_modules\b
luebird\js\main\promise.js:999:10)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (C:\Users\ALERA
TOR\AppData\Roaming\npm\node_modules\meteor-now\node_modules\promise-spawner\no
de_modules\bluebird\js\main\async.js:74:12)
    at Async$consumeFunctionBuffer (C:\Users\ALERATOR\AppData\Roaming\npm\node_
modules\meteor-now\node_modules\promise-spawner\node_modules\bluebird\js\main\a
sync.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
⢃⠨
```

**Comment by purplecones** [comment]
Try deploying with -d flag. There is a bug where deploying on free accounts without it hangs. It's due to the prompt now asks during deploys on free account. 

-
MJ

**Comment by janat08** [comment]
that worked.

**Comment by janat08** [comment]
Perhaps this option should be enabled if free account is detected?
