### ISSUE TITLE
Cannot read property 'getDeployments' of undefined

### ISSUE THREAD

**Issue by Lukasvo** [jkrup/meteor-now#70]
I get the following errors when trying to deploy.
I've tried
- `rm -rf node_modules && meteor npm install && meteor reset`
- making a .now.json file (what should the actual content be?) to supplying a token in the command with -t or --token
- getting a new token

What am I doing wrong?
Thanks.

`meteor-now -e 'MONGO_URL=mongodb://XXX' -d --public [--token XXX]`

```
[METEOR-NOW] - getting deployment url...
Error: Error: Cannot find module '/Users/lukasvo/.now.json'
No token found! Supply it as argument or use the NOW_TOKEN env variable. `~/.now.json` will be used, if it's found in your home directory.
TypeError: Cannot read property 'getDeployments' of undefined
    at _callee8$ (/usr/local/lib/node_modules/meteor-now/dist/app.js:341:24)
    at tryCatch (/usr/local/lib/node_modules/meteor-now/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/meteor-now/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/meteor-now/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/meteor-now/dist/app.js:97:192)
    at /usr/local/lib/node_modules/meteor-now/dist/app.js:97:438
    at /usr/local/lib/node_modules/meteor-now/dist/app.js:97:100
    at getDeploymentUrl (/usr/local/lib/node_modules/meteor-now/dist/app.js:368:19)
    at _callee11$ (/usr/local/lib/node_modules/meteor-now/dist/app.js:459:21)
    at tryCatch (/usr/local/lib/node_modules/meteor-now/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/meteor-now/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/meteor-now/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/meteor-now/dist/app.js:97:192)
    at /usr/local/lib/node_modules/meteor-now/dist/app.js:97:362
    at process._tickCallback (internal/process/next_tick.js:109:7)
[METEOR-NOW] - cleaning up
TypeError: Cannot read property 'url' of undefined
    at _callee11$ (/usr/local/lib/node_modules/meteor-now/dist/app.js:467:78)
    at tryCatch (/usr/local/lib/node_modules/meteor-now/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/meteor-now/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/meteor-now/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/meteor-now/dist/app.js:97:192)
    at /usr/local/lib/node_modules/meteor-now/dist/app.js:97:362
```

**Comment by purplecones** [comment]
It looks like you never logged into now. Did you do `$ now --login` first ?

**Comment by Lukasvo** [comment]
I did. Verification by email and everything.
After login, I get "Ready! Authentication token and personal details saved in "~/.now".
So, no .now.json file was generated.

**Comment by purplecones** [comment]
What do you get when you run 'now ls' ?

-
MJ

**Comment by Lukasvo** [comment]
Thanks for your help, MJ.

```
3 deployments found under xxx [3s]

"xxx" (3 of 3 total)
 url                                  inst #    state                 age
 xxx-vsxzekmaoq.now.sh              0    DEPLOYMENT_ERROR      23h
 xxx-lcfzhlrfee.now.sh              0    DEPLOYMENT_ERROR      24h
 xxx-cylegiksor.now.sh              0    DEPLOYING             24h
```

**Comment by purplecones** [comment]
We pushed a new version of `meteor-now`. Can you update to the latest and try again?

**Comment by purplecones** [comment]
Assuming issue is no longer relevant with latest release. Closing.
