### ISSUE TITLE
deployment hangs [SOLVED]

### ISSUE THREAD

**Issue by acomito** [jkrup/meteor-now#71]
`✔ [METEOR-NOW] - building meteor app

✔ [METEOR-NOW] - preparing build

⠄⡙ [METEOR-NOW] - deploying build (this can take several minutes)Possibly unhandled Error: 1
    at Promise$_rejecter (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:590:44)
    at /usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/index.js:85:13
    at tryCatch1 (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:1006:14)
    at Promise$_rejectPromises [as _rejectPromises] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:999:10)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/async.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
⢂⠩ [METEOR-NOW] - deploying build (this can take several minutes)`

I'm not sure what I'm missing here. I feel like I ran into this in the past and solved it, but don't recall how.

**Comment by acomito** [comment]
Lesson: Always search the issues first 


https://github.com/jkrup/meteor-now/issues/57

**Comment by purplecones** [comment]
This should be fixed in the latest version of `meteor-now`. Please reopen if you still have this issue.
