### ISSUE TITLE
bluebird promise error

### ISSUE THREAD

**Issue by webmagnets** [jkrup/meteor-now#76]
I am getting this error when trying to deploy:

```
> Removing intermediate container 5cbc74947ff1
> Step 6 : RUN tar -xzf bundle.tar.gz
>  ---> Running in 66cce42f71d5
> 
> gzip: stdin: decompression OK, trailing garbage ignored
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now
> The command '/bin/sh -c tar -xzf bundle.tar.gz' returned a non-zero code: 2
> Error! The build step of your project failed. To retry, run `now --force`.
Possibly unhandled Error: 1
    at Promise$_rejecter (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:590:44)
    at /usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/index.js:85:13
    at tryCatch1 (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:1006:14)
    at Promise$_rejectPromises [as _rejectPromises] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/promise.js:999:10)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/async.js:74:12)
    at Async$consumeFunctionBuffer (/usr/local/lib/node_modules/meteor-now/node_modules/promise-spawner/node_modules/bluebird/js/main/async.js:37:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

Any ideas?

**Comment by purplecones** [comment]
We pushed a new version of `meteor-now`. Can you update to the latest and try again?

**Comment by purplecones** [comment]
Assuming issue is no longer relevant with latest release. Closing.
