### ISSUE TITLE
meteor-now complain Unexpected Token

### ISSUE THREAD

**Issue by lesliedoghouse** [jkrup/meteor-now#86]
The following is the error whenever I run "meteor-now", please advice:

macOS:Admin-BPW macuser$ meteor-now
/Users/macuser/.nvm/versions/node/v4.8.4/lib/node_modules/meteor-now/build/main.js:88
const getArgs = exports.getArgs = (argv = process.argv) => (0, _yargs2.default)(argv).argv;
                                        ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

**Comment by purplecones** [comment]
Try upgrading your node version to 6 and above rerun.

**Comment by lesliedoghouse** [comment]
Hi, upgrade to Node v6 solved the problem. 

Now I got "[METEOR-NOW] - Something went wrong with now"

**Comment by purplecones** [comment]
Is this still a problem?
