### ISSUE TITLE
Object.getOwnPropertyDescriptors is not a function (502 Error)

### ISSUE THREAD

**Issue by janat08** [jkrup/meteor-now#95]
Returns 502 even after mongo has become connected, I think. now-v at 8.4, meteor 1.6.1-rc.7, meteor-now 0.5.1 doesn't work.
```
2018-01-17 05:21:37,538 DEBG 'node' stderr output:
/usr/src/app/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Object.getOwnPropertyDescriptors is not a function
    at insert (packages/mongo/collection.js:435:12)
    at AccountsServer.Ap.insertUserDoc (packages/accounts-base/accounts_server.js:1340:25)
    at createUser (packages/accounts-password/password_server.js:1054:25)
    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1123:10)
    at main.js (server/main.js:44:14)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /usr/src/app/bundle/programs/server/app/app.js:478:1
    at infos.forEach.info (/usr/src/app/bundle/programs/server/boot.js:414:13)
    at Array.forEach (native)
```

**Comment by janat08** [comment]
All the logs:
```
01/17 11:31 AM (18s)

2018-01-17 05:31:07,460 DEBG 'node' stderr output:
/usr/src/app/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Object.getOwnPropertyDescriptors is not a function
    at insert (packages/mongo/collection.js:435:12)
    at AccountsServer.Ap.insertUserDoc (packages/accounts-base/accounts_server.js:1340:25)
    at createUser (packages/accounts-password/password_server.js:1054:25)
    at AccountsServer.Accounts.createUser (packages/accounts-password/password_server.js:1123:10)
    at main.js (server/main.js:44:14)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /usr/src/app/bundle/programs/server/app/app.js:478:1
    at infos.forEach.info (/usr/src/app/bundle/programs/server/boot.js:414:13)
    at Array.forEach (native)
01/17 11:31 AM (18s)

2018-01-17 05:31:07,464 DEBG 'mongo' stdout output:
Wed Jan 17 05:31:07.464 [conn325] end connection 127.0.0.1:49714 (1 connection now open)
Wed Jan 17 05:31:07.464 [conn326] end connection 127.0.0.1:49722 (1 connection now open)
01/17 11:31 AM (18s)

2018-01-17 05:31:07,464 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140286531225792 for <Subprocess at 140286531632952 with name node in state RUNNING> (stderr)>
2018-01-17 05:31:07,464 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 140286531222704 for <Subprocess at 140286531632952 with name node in state RUNNING> (stdout)>
2018-01-17 05:31:07,464 INFO exited: node (exit status 1; not expected)
2018-01-17 05:31:07,464 DEBG received SIGCLD indicating a child quit
01/17 11:31 AM (17s)
2018-01-17 05:31:08,467 INFO spawned: 'node' with pid 2242
01/17 11:31 AM (16s)
2018-01-17 05:31:09,513 INFO success: node entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
01/17 11:31 AM (16s)
2018-01-17 05:31:10,113 DEBG 'mongo' stdout output:
Wed Jan 17 05:31:10.113 [initandlisten] connection accepted from 127.0.0.1:49766 #327 (1 connection now open)
01/17 11:31 AM (16s)

2018-01-17 05:31:10,222 DEBG 'node' stderr output:
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
01/17 11:31 AM (15s)

2018-01-17 05:31:10,449 DEBG 'node' stdout output:
** You've set up some data subscriptions with Meteor.publish(), but
** you still have autopublish turned on. Because autopublish is still
** on, your Meteor.publish() calls won't have much effect. All data
** will still be sent to all clients.
**
** Turn off autopublish by removing the autopublish package:
**
**   $ meteor remove autopublish
**
** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
** for each collection that you want clients to see.
```

**Comment by janat08** [comment]
https://github.com/meteor/meteor/issues/9470

**Comment by janat08** [comment]
btw I'm running latest version.

**Comment by jkrup** [comment]
You're running `meteor-now@0.5.3` and still experiencing this issue?

**Comment by janat08** [comment]
+-- meteor-now@0.5.3

**Comment by janat08** [comment]
`-- meteor-now@0.5.3 on "meteor npm"

**Comment by jkrup** [comment]
Could you try `npm install -g meteor-now@0.5.3`? Perhaps your globally installed meteor-now is not at 0.5.3

**Comment by janat08** [comment]
Right the windows install doesn't work at all, and that's where I was checking the versions, meanwhile, I actually deployed from linux vm which is outdated.
